languageCode = "en-us"
disableKinds = [ "RSS" ]
title = "BigTech.fail"
enableEmoji = true
summaryLength = 25

[frontmatter]
	lastmod = [ ":git", "lastmod" ]

[minify]
	minifyOutput = true

[taxonomies]
	tag = "tags"
	profile = "profiles"
	corpos = "corpos"
	alttr = "alttrs"

[permalinks]
	corpos = "/:slug/"
	events = "/e/:filename/"
	tags = "/t/:slug/"
	alttrs = "/alt/:slug/"
	alts = "/alt/:slug"

[markup.goldmark.renderer]
	unsafe= true
