languageCode = "en-us"
title = "BigTech.fail"
enableEmoji = true

[minify]
	minifyOutput = true

[taxonomies]
	profile = "profiles"
	platform = "platforms"

[permalinks]
	platforms = "/:slug/"

[markup.goldmark.renderer]
unsafe= true
