languageCode = "en-us"
disableKinds = [ "RSS" ]
title = "BigTech.fail"
enableEmoji = true

[minify]
	minifyOutput = true

[taxonomies]
	profile = "profiles"
	altfor = "altfor"
	platform = "platforms"

[permalinks]
	platforms = "/:slug/"
	altfor = "/:slug/alts"

[markup.goldmark.renderer]
	unsafe= true
