languageCode = "en-us"
disableKinds = [ "RSS" ]
title = "BigTech.fail"
enableEmoji = true
summaryLength = 25

[frontmatter]
	lastmod = [ ":git", "lastmod" ]

[minify]
	minifyOutput = true

[taxonomies]
	tag = "tags"
	profile = "profiles"
	altfor = "altfor"
	platform = "platforms"

[permalinks]
	platforms = "/:slug/"
	altfor = "/:slug/alts"

[markup.goldmark.renderer]
	unsafe= true
